use crate::gameboy_cpu::*;

pub enum Opcode {
    Invalid,
    NOP,
    LD,
    ADD,
    ADC,
    INC,
    DEC,
    RLCA,
    RRA,
    JR,
    RRCA,
    STOP,
    RLA,
    LDI,
    DAA,
    CPL,
    LDD,
    SCF,
    CCF,
    HALT,
    SUB,
    SBC,
    AND,
    XOR,
    OR,
    CP,
    RET,
    POP,
    JP,
    CALL,
    PUSH,
    RST,
    PREFIX,
    RETI,
    LDH,
    DI,
    LDHL,
    EI,
}

pub enum Operand {
    Value(Reg),
    DerefReg(Reg),
    Imm8,
    Imm8Signed,
    DerefImm8,
    Imm16,
    DerefImm16,
    Rst00H,
    Rst08H,
    Rst10H,
    Rst18H,
    Rst20H,
    Rst28H,
    Rst30H,
    Rst38H,
    FlagNC,
    FlagNZ,
    FlagC,
    FlagZ,
    None,
}

pub struct Instr {
    opr: Opcode,
    dst: Operand,
    src: Operand,
    cycles: usize,
}

impl Instr {
    const fn create(opr: Opcode, dst: Operand, src: Operand, cycles: usize) -> Self {
        Instr {
            opr,
            dst,
            src,
            cycles,
        }
    }
}

#[rustfmt::skip]
pub const INSTRUCTION_LOOKUP: [Instr; 256] = [
    /* 0x00 */ Instr::create(Opcode::NOP    , Operand::None             , Operand::None             , 4),
    /* 0x01 */ Instr::create(Opcode::LD     , Operand::Value(Reg::BC)   , Operand::Imm16            , 12),
    /* 0x02 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::BC), Operand::Value(Reg::A)    , 8),
    /* 0x03 */ Instr::create(Opcode::INC    , Operand::Value(Reg::BC)   , Operand::None             , 8),
    /* 0x04 */ Instr::create(Opcode::INC    , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0x05 */ Instr::create(Opcode::DEC    , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0x06 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Imm8             , 8),
    /* 0x07 */ Instr::create(Opcode::RLCA   , Operand::None             , Operand::None             , 4),
    /* 0x08 */ Instr::create(Opcode::LD     , Operand::DerefImm16       , Operand::Value(Reg::SP)   , 20),
    /* 0x09 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::HL)   , Operand::Value(Reg::BC)   , 8),
    /* 0x0A */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::BC), 8),
    /* 0x0B */ Instr::create(Opcode::DEC    , Operand::Value(Reg::BC)   , Operand::None             , 8),
    /* 0x0C */ Instr::create(Opcode::INC    , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0x0D */ Instr::create(Opcode::DEC    , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0x0E */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Imm8             , 8),
    /* 0x0F */ Instr::create(Opcode::RRCA   , Operand::None             , Operand::None             , 4),
    /* 0x10 */ Instr::create(Opcode::STOP   , Operand::None             , Operand::None             , 4),
    /* 0x11 */ Instr::create(Opcode::LD     , Operand::Value(Reg::DE)   , Operand::Imm16            , 12),
    /* 0x12 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::DE), Operand::Value(Reg::A)    , 8),
    /* 0x13 */ Instr::create(Opcode::INC    , Operand::Value(Reg::DE)   , Operand::None             , 8),
    /* 0x14 */ Instr::create(Opcode::INC    , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0x15 */ Instr::create(Opcode::DEC    , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0x16 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Imm8             , 8),
    /* 0x17 */ Instr::create(Opcode::RLA    , Operand::None             , Operand::None             , 4),
    /* 0x18 */ Instr::create(Opcode::JR     , Operand::Imm8Signed       , Operand::None             , 12),
    /* 0x19 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::HL)   , Operand::Value(Reg::DE)   , 8),
    /* 0x1A */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::DE), 8),
    /* 0x1B */ Instr::create(Opcode::DEC    , Operand::Value(Reg::DE)   , Operand::None             , 8),
    /* 0x1C */ Instr::create(Opcode::INC    , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0x1D */ Instr::create(Opcode::DEC    , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0x1E */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Imm8             , 8),
    /* 0x1F */ Instr::create(Opcode::RRA    , Operand::None             , Operand::None             , 4),
    /* 0x20 */ Instr::create(Opcode::JR     , Operand::FlagNZ           , Operand::Imm8Signed       , 12),
    /* 0x21 */ Instr::create(Opcode::LD     , Operand::Value(Reg::HL)   , Operand::Imm16            , 12),
    /* 0x22 */ Instr::create(Opcode::LDI    , Operand::DerefReg(Reg::HL), Operand::Value(Reg::A)    , 8),
    /* 0x23 */ Instr::create(Opcode::INC    , Operand::Value(Reg::HL)   , Operand::None             , 8),
    /* 0x24 */ Instr::create(Opcode::INC    , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0x25 */ Instr::create(Opcode::DEC    , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0x26 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Imm8             , 8),
    /* 0x27 */ Instr::create(Opcode::DAA    , Operand::None             , Operand::None             , 4),
    /* 0x28 */ Instr::create(Opcode::JR     , Operand::FlagZ            , Operand::Imm8Signed       , 12),
    /* 0x29 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::HL)   , Operand::Value(Reg::HL)   , 8),
    /* 0x2A */ Instr::create(Opcode::LDI    , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x2B */ Instr::create(Opcode::DEC    , Operand::Value(Reg::HL)   , Operand::None             , 8),
    /* 0x2C */ Instr::create(Opcode::INC    , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0x2D */ Instr::create(Opcode::DEC    , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0x2E */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Imm8             , 8),
    /* 0x2F */ Instr::create(Opcode::CPL    , Operand::None             , Operand::None             , 4),
    /* 0x30 */ Instr::create(Opcode::JR     , Operand::FlagNC           , Operand::Imm8Signed       , 12),
    /* 0x31 */ Instr::create(Opcode::LD     , Operand::Value(Reg::SP)   , Operand::Imm16            , 12),
    /* 0x32 */ Instr::create(Opcode::LDD    , Operand::DerefReg(Reg::HL), Operand::Value(Reg::A)    , 8),
    /* 0x33 */ Instr::create(Opcode::INC    , Operand::Value(Reg::SP)   , Operand::None             , 8),
    /* 0x34 */ Instr::create(Opcode::INC    , Operand::DerefReg(Reg::HL), Operand::None             , 12),
    /* 0x35 */ Instr::create(Opcode::DEC    , Operand::DerefReg(Reg::HL), Operand::None             , 12),
    /* 0x36 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Imm8             , 12),
    /* 0x37 */ Instr::create(Opcode::SCF    , Operand::None             , Operand::None             , 4),
    /* 0x38 */ Instr::create(Opcode::JR     , Operand::FlagC            , Operand::Imm8Signed       , 12),
    /* 0x39 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::HL)   , Operand::Value(Reg::SP)   , 8),
    /* 0x3A */ Instr::create(Opcode::LDD    , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x3B */ Instr::create(Opcode::DEC    , Operand::Value(Reg::SP)   , Operand::None             , 8),
    /* 0x3C */ Instr::create(Opcode::INC    , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0x3D */ Instr::create(Opcode::DEC    , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0x3E */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Imm8             , 8),
    /* 0x3F */ Instr::create(Opcode::CCF    , Operand::None             , Operand::None             , 4),
    /* 0x40 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::B)    , 4),
    /* 0x41 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::C)    , 4),
    /* 0x42 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::D)    , 4),
    /* 0x43 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::E)    , 4),
    /* 0x44 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::H)    , 4),
    /* 0x45 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::L)    , 4),
    /* 0x46 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x47 */ Instr::create(Opcode::LD     , Operand::Value(Reg::B)    , Operand::Value(Reg::A)    , 4),
    /* 0x48 */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::B)    , 4),
    /* 0x49 */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::C)    , 4),
    /* 0x4A */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::D)    , 4),
    /* 0x4B */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::E)    , 4),
    /* 0x4C */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::H)    , 4),
    /* 0x4D */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::L)    , 4),
    /* 0x4E */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x4F */ Instr::create(Opcode::LD     , Operand::Value(Reg::C)    , Operand::Value(Reg::A)    , 4),
    /* 0x50 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::B)    , 4),
    /* 0x51 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::C)    , 4),
    /* 0x52 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::D)    , 4),
    /* 0x53 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::E)    , 4),
    /* 0x54 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::H)    , 4),
    /* 0x55 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::L)    , 4),
    /* 0x56 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x57 */ Instr::create(Opcode::LD     , Operand::Value(Reg::D)    , Operand::Value(Reg::A)    , 4),
    /* 0x58 */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::B)    , 4),
    /* 0x59 */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::C)    , 4),
    /* 0x5A */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::D)    , 4),
    /* 0x5B */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::E)    , 4),
    /* 0x5C */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::H)    , 4),
    /* 0x5D */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::L)    , 4),
    /* 0x5E */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x5F */ Instr::create(Opcode::LD     , Operand::Value(Reg::E)    , Operand::Value(Reg::A)    , 4),
    /* 0x60 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::B)    , 4),
    /* 0x61 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::C)    , 4),
    /* 0x62 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::D)    , 4),
    /* 0x63 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::E)    , 4),
    /* 0x64 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::H)    , 4),
    /* 0x65 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::L)    , 4),
    /* 0x66 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x67 */ Instr::create(Opcode::LD     , Operand::Value(Reg::H)    , Operand::Value(Reg::A)    , 4),
    /* 0x68 */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::B)    , 4),
    /* 0x69 */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::C)    , 4),
    /* 0x6A */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::D)    , 4),
    /* 0x6B */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::E)    , 4),
    /* 0x6C */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::H)    , 4),
    /* 0x6D */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::L)    , 4),
    /* 0x6E */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x6F */ Instr::create(Opcode::LD     , Operand::Value(Reg::L)    , Operand::Value(Reg::A)    , 4),
    /* 0x70 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::B)    , 8),
    /* 0x71 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::C)    , 8),
    /* 0x72 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::D)    , 8),
    /* 0x73 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::E)    , 8),
    /* 0x74 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::H)    , 8),
    /* 0x75 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::L)    , 8),
    /* 0x76 */ Instr::create(Opcode::HALT   , Operand::None             , Operand::None             , 4),
    /* 0x77 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::HL), Operand::Value(Reg::A)    , 8),
    /* 0x78 */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::B)    , 4),
    /* 0x79 */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::C)    , 4),
    /* 0x7A */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::D)    , 4),
    /* 0x7B */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::E)    , 4),
    /* 0x7C */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::H)    , 4),
    /* 0x7D */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::L)    , 4),
    /* 0x7E */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x7F */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::Value(Reg::A)    , 4),
    /* 0x80 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::B)    , 4),
    /* 0x81 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::C)    , 4),
    /* 0x82 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::D)    , 4),
    /* 0x83 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::E)    , 4),
    /* 0x84 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::H)    , 4),
    /* 0x85 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::L)    , 4),
    /* 0x86 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x87 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Value(Reg::A)    , 4),
    /* 0x88 */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::B)    , 4),
    /* 0x89 */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::C)    , 4),
    /* 0x8A */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::D)    , 4),
    /* 0x8B */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::E)    , 4),
    /* 0x8C */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::H)    , 4),
    /* 0x8D */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::L)    , 4),
    /* 0x8E */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x8F */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Value(Reg::A)    , 4),
    /* 0x90 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0x91 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0x92 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0x93 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0x94 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0x95 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0x96 */ Instr::create(Opcode::SUB    , Operand::DerefReg(Reg::HL), Operand::None             , 8),
    /* 0x97 */ Instr::create(Opcode::SUB    , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0x98 */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::B)    , 4),
    /* 0x99 */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::C)    , 4),
    /* 0x9A */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::D)    , 4),
    /* 0x9B */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::E)    , 4),
    /* 0x9C */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::H)    , 4),
    /* 0x9D */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::L)    , 4),
    /* 0x9E */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::HL), 8),
    /* 0x9F */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Value(Reg::A)    , 4),
    /* 0xA0 */ Instr::create(Opcode::AND    , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0xA1 */ Instr::create(Opcode::AND    , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0xA2 */ Instr::create(Opcode::AND    , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0xA3 */ Instr::create(Opcode::AND    , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0xA4 */ Instr::create(Opcode::AND    , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0xA5 */ Instr::create(Opcode::AND    , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0xA6 */ Instr::create(Opcode::AND    , Operand::DerefReg(Reg::HL), Operand::None             , 8),
    /* 0xA7 */ Instr::create(Opcode::AND    , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0xA8 */ Instr::create(Opcode::XOR    , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0xA9 */ Instr::create(Opcode::XOR    , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0xAA */ Instr::create(Opcode::XOR    , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0xAB */ Instr::create(Opcode::XOR    , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0xAC */ Instr::create(Opcode::XOR    , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0xAD */ Instr::create(Opcode::XOR    , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0xAE */ Instr::create(Opcode::XOR    , Operand::DerefReg(Reg::HL), Operand::None             , 8),
    /* 0xAF */ Instr::create(Opcode::XOR    , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0xB0 */ Instr::create(Opcode::OR     , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0xB1 */ Instr::create(Opcode::OR     , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0xB2 */ Instr::create(Opcode::OR     , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0xB3 */ Instr::create(Opcode::OR     , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0xB4 */ Instr::create(Opcode::OR     , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0xB5 */ Instr::create(Opcode::OR     , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0xB6 */ Instr::create(Opcode::OR     , Operand::DerefReg(Reg::HL), Operand::None             , 8),
    /* 0xB7 */ Instr::create(Opcode::OR     , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0xB8 */ Instr::create(Opcode::CP     , Operand::Value(Reg::B)    , Operand::None             , 4),
    /* 0xB9 */ Instr::create(Opcode::CP     , Operand::Value(Reg::C)    , Operand::None             , 4),
    /* 0xBA */ Instr::create(Opcode::CP     , Operand::Value(Reg::D)    , Operand::None             , 4),
    /* 0xBB */ Instr::create(Opcode::CP     , Operand::Value(Reg::E)    , Operand::None             , 4),
    /* 0xBC */ Instr::create(Opcode::CP     , Operand::Value(Reg::H)    , Operand::None             , 4),
    /* 0xBD */ Instr::create(Opcode::CP     , Operand::Value(Reg::L)    , Operand::None             , 4),
    /* 0xBE */ Instr::create(Opcode::CP     , Operand::DerefReg(Reg::HL), Operand::None             , 8),
    /* 0xBF */ Instr::create(Opcode::CP     , Operand::Value(Reg::A)    , Operand::None             , 4),
    /* 0xC0 */ Instr::create(Opcode::RET    , Operand::FlagNZ           , Operand::None             , 20),
    /* 0xC1 */ Instr::create(Opcode::POP    , Operand::Value(Reg::BC)   , Operand::None             , 12),
    /* 0xC2 */ Instr::create(Opcode::JP     , Operand::FlagNZ           , Operand::Imm16            , 16),
    /* 0xC3 */ Instr::create(Opcode::JP     , Operand::Imm16            , Operand::None             , 16),
    /* 0xC4 */ Instr::create(Opcode::CALL   , Operand::FlagNZ           , Operand::Imm16            , 24),
    /* 0xC5 */ Instr::create(Opcode::PUSH   , Operand::Value(Reg::BC)   , Operand::None             , 16),
    /* 0xC6 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::A)    , Operand::Imm8             , 8),
    /* 0xC7 */ Instr::create(Opcode::RST    , Operand::Rst00H           , Operand::None             , 16),
    /* 0xC8 */ Instr::create(Opcode::RET    , Operand::FlagZ            , Operand::None             , 20),
    /* 0xC9 */ Instr::create(Opcode::RET    , Operand::None             , Operand::None             , 16),
    /* 0xCA */ Instr::create(Opcode::JP     , Operand::FlagZ            , Operand::Imm16            , 16),
    /* 0xCB */ Instr::create(Opcode::PREFIX , Operand::None             , Operand::None             , 4),
    /* 0xCC */ Instr::create(Opcode::CALL   , Operand::FlagZ            , Operand::Imm16            , 24),
    /* 0xCD */ Instr::create(Opcode::CALL   , Operand::Imm16            , Operand::None             , 24),
    /* 0xCE */ Instr::create(Opcode::ADC    , Operand::Value(Reg::A)    , Operand::Imm8             , 8),
    /* 0xCF */ Instr::create(Opcode::RST    , Operand::Rst08H           , Operand::None             , 16),
    /* 0xD0 */ Instr::create(Opcode::RET    , Operand::FlagNC           , Operand::None             , 20),
    /* 0xD1 */ Instr::create(Opcode::POP    , Operand::Value(Reg::DE)   , Operand::None             , 12),
    /* 0xD2 */ Instr::create(Opcode::JP     , Operand::FlagNC           , Operand::Imm16            , 16),
    /* 0xD3 */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xD4 */ Instr::create(Opcode::CALL   , Operand::FlagNC           , Operand::Imm16            , 24),
    /* 0xD5 */ Instr::create(Opcode::PUSH   , Operand::Value(Reg::DE)   , Operand::None             , 16),
    /* 0xD6 */ Instr::create(Opcode::SUB    , Operand::Imm8             , Operand::None             , 8),
    /* 0xD7 */ Instr::create(Opcode::RST    , Operand::Rst10H           , Operand::None             , 16),
    /* 0xD8 */ Instr::create(Opcode::RET    , Operand::FlagC            , Operand::None             , 20),
    /* 0xD9 */ Instr::create(Opcode::RETI   , Operand::None             , Operand::None             , 16),
    /* 0xDA */ Instr::create(Opcode::JP     , Operand::FlagC            , Operand::Imm16            , 16),
    /* 0xDB */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xDC */ Instr::create(Opcode::CALL   , Operand::FlagC            , Operand::Imm16            , 24),
    /* 0xDD */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xDE */ Instr::create(Opcode::SBC    , Operand::Value(Reg::A)    , Operand::Imm8             , 8),
    /* 0xDF */ Instr::create(Opcode::RST    , Operand::Rst18H           , Operand::None             , 16),
    /* 0xE0 */ Instr::create(Opcode::LDH    , Operand::DerefImm8        , Operand::Value(Reg::A)    , 12),
    /* 0xE1 */ Instr::create(Opcode::POP    , Operand::Value(Reg::HL)   , Operand::None             , 12),
    /* 0xE2 */ Instr::create(Opcode::LD     , Operand::DerefReg(Reg::C) , Operand::Value(Reg::A)    , 8),
    /* 0xE3 */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xE4 */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xE5 */ Instr::create(Opcode::PUSH   , Operand::Value(Reg::HL)   , Operand::None             , 16),
    /* 0xE6 */ Instr::create(Opcode::AND    , Operand::Imm8             , Operand::None             , 8),
    /* 0xE7 */ Instr::create(Opcode::RST    , Operand::Rst20H           , Operand::None             , 16),
    /* 0xE8 */ Instr::create(Opcode::ADD    , Operand::Value(Reg::SP)   , Operand::Imm8Signed       , 16),
    /* 0xE9 */ Instr::create(Opcode::JP     , Operand::Value(Reg::HL)   , Operand::None             , 4),
    /* 0xEA */ Instr::create(Opcode::LD     , Operand::DerefImm16       , Operand::Value(Reg::A)    , 16),
    /* 0xEB */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xEC */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xED */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xEE */ Instr::create(Opcode::XOR    , Operand::Imm8             , Operand::None             , 8),
    /* 0xEF */ Instr::create(Opcode::RST    , Operand::Rst28H           , Operand::None             , 16),
    /* 0xF0 */ Instr::create(Opcode::LDH    , Operand::Value(Reg::A)    , Operand::DerefImm8        , 12),
    /* 0xF1 */ Instr::create(Opcode::POP    , Operand::Value(Reg::AF)   , Operand::None             , 12),
    /* 0xF2 */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::DerefReg(Reg::C) , 8),
    /* 0xF3 */ Instr::create(Opcode::DI     , Operand::None             , Operand::None             , 4),
    /* 0xF4 */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xF5 */ Instr::create(Opcode::PUSH   , Operand::Value(Reg::AF)   , Operand::None             , 16),
    /* 0xF6 */ Instr::create(Opcode::OR     , Operand::Imm8             , Operand::None             , 8),
    /* 0xF7 */ Instr::create(Opcode::RST    , Operand::Rst30H           , Operand::None             , 16),
    /* 0xF8 */ Instr::create(Opcode::LDHL   , Operand::Value(Reg::SP)   , Operand::Imm8Signed       , 12),
    /* 0xF9 */ Instr::create(Opcode::LD     , Operand::Value(Reg::SP)   , Operand::Value(Reg::HL)   , 8),
    /* 0xFA */ Instr::create(Opcode::LD     , Operand::Value(Reg::A)    , Operand::DerefImm16       , 16),
    /* 0xFB */ Instr::create(Opcode::EI     , Operand::None             , Operand::None             , 4),
    /* 0xFC */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xFD */ Instr::create(Opcode::Invalid, Operand::None             , Operand::None             , 0),
    /* 0xFE */ Instr::create(Opcode::CP     , Operand::Imm8             , Operand::None             , 8),
    /* 0xFF */ Instr::create(Opcode::RST    , Operand::Rst38H           , Operand::None             , 16),
];
